backend:
    name: github
    repo: jaubut/maman_web
    branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "/img/uploads"
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "notification" # Used in routes, e.g. /admin/collections/blog
    label: "notification" # Used in the UI
    folder: "index/notifications" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Body", name: "message", widget: "text"}
      - {label: "Class", name: "dotcolor", widget: "text"}
      - {label: "Statue", name: "statue", widget: "text"}